spring:
  profiles:
    active: dev
  http:
    multipart:
      max-file-size: 128KB
      max-request-size: 128KB
server:
  port: 9000
#  mybatis映射关系
mybatis:
    type-aliases-package: com.together.model.po
    mapper-locations: classpath:mapper/*.xml
#  日志配置
logging:
    config: classpath:logback.xml

---
#  debug模式
#debug: true
spring:
#  profiles配置
  profiles: debug
#  datasource配置
  datasource:
    url: jdbc:mysql://192.168.1.171:3306/together?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root

---
#  debug模式
spring:
#  profiles配置
  profiles: dev
#  datasource配置
  datasource:
    url: jdbc:mysql://rm-2zee86bcra94k9z2w.mysql.rds.aliyuncs.com:3306/together?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: bairuifei
    password: XZtx2016